version: 2.1

orbs:
  node: circleci/node@4.2.1
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: installing packages
          command: |
            yarn install
      - run:
          name: Running tests
          command: |
            yarn test

workflows:
  ship-software:
    jobs:
      - build-and-test
    on: push
    matrix:
      node: ['14.x', '16.x', '18.x']
      os: [ubuntu-latest, windows-latest, macos-latest]
    secrets:
      FINCRA_PUBLIC_KEY:
        default: ${{ secrets.FINCRA_PUBLIC_KEY }}
      FINCRA_SECRET_KEY:
        default: ${{ secrets.FINCRA_SECRET_KEY }}
    retry:
      allow_failures: true
      on: push
        pull_request
      attempts:
        max: 3
        interval:
          minutes: 5
      delay:
        minutes: 5
