version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: installing packages
          command: |
            npm install
      - run:
          name: Running tests
          command: |
            npm run test

workflows:
  ship-software:
    jobs:
      - build-and-test
