version: 2.1

orbs:
  node: circleci/node@4.2.1
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: installing packages
          command: |
            if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi
      - run:
          name: Running tests
          command: |
            yarn test

workflows:
  ship-software:
    jobs:
      - build-and-test
