version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Running tests
          command: |
            yarn test

workflows:
  ship-software:
    jobs:
      - build-and-test:

